create table if not exists portfolio_profile (
  id smallint primary key default 1 check (id = 1),
  first_name text not null,
  last_name text not null,
  headline text not null,
  positioning text not null,
  favorite_stack text not null,
  location text not null,
  photo_url text default '',
  email text not null,
  phone_link text not null,
  phone_display text not null,
  github_url text not null,
  github_label text not null,
  legacy_portfolio_url text not null,
  contact_note text not null
);

create table if not exists portfolio_about (
  id smallint primary key default 1 check (id = 1),
  title text not null,
  paragraphs text[] not null default '{}'
);

create table if not exists portfolio_highlights (
  id bigint generated by default as identity primary key,
  text text not null,
  display_order int not null default 0
);

create table if not exists portfolio_experiences (
  id bigint generated by default as identity primary key,
  period text not null,
  title text not null,
  description text not null,
  display_order int not null default 0
);

create table if not exists portfolio_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  stack text not null default '',
  image text not null default '',
  url text not null,
  link_label text not null,
  display_order int not null default 0
);

create table if not exists portfolio_skills (
  id bigint generated by default as identity primary key,
  label text not null,
  description text not null,
  display_order int not null default 0
);

revoke all on portfolio_profile from anon, authenticated;
revoke all on portfolio_about from anon, authenticated;
revoke all on portfolio_highlights from anon, authenticated;
revoke all on portfolio_experiences from anon, authenticated;
revoke all on portfolio_projects from anon, authenticated;
revoke all on portfolio_skills from anon, authenticated;

grant select on portfolio_profile to anon, authenticated;
grant select on portfolio_about to anon, authenticated;
grant select on portfolio_highlights to anon, authenticated;
grant select on portfolio_experiences to anon, authenticated;
grant select on portfolio_projects to anon, authenticated;
grant select on portfolio_skills to anon, authenticated;

alter table portfolio_profile enable row level security;
alter table portfolio_about enable row level security;
alter table portfolio_highlights enable row level security;
alter table portfolio_experiences enable row level security;
alter table portfolio_projects enable row level security;
alter table portfolio_skills enable row level security;

create policy "public_read_portfolio_profile"
on portfolio_profile
for select
to anon, authenticated
using (true);

create policy "public_read_portfolio_about"
on portfolio_about
for select
to anon, authenticated
using (true);

create policy "public_read_portfolio_highlights"
on portfolio_highlights
for select
to anon, authenticated
using (true);

create policy "public_read_portfolio_experiences"
on portfolio_experiences
for select
to anon, authenticated
using (true);

create policy "public_read_portfolio_projects"
on portfolio_projects
for select
to anon, authenticated
using (true);

create policy "public_read_portfolio_skills"
on portfolio_skills
for select
to anon, authenticated
using (true);
